version: 0.2

phases:
  install:
    commands:
      # this is here for debug purposes
      - printenv

  pre_build:
    commands:
      - dotnet restore ExampleProject.sln
  build:
    commands:
      - dotnet build ExampleProject.sln -c Release

      - dotnet test ./LambdaFunction/test/LambdaFunction.UnitTests -c Release --no-build
      - mv ./LambdaFunction/test/LambdaFunction.UnitTests/bin/Release/netcoreapp2.1/BDDfy.html ./LambdaFunction-Unit-Tests.html

      - dotnet publish ./LambdaFunction/src/LambdaFunction/ --no-build -c Release -o ../../../publish/lambda

artifacts:
  type: zip
  files:
    - ExampleProject.yaml
    - LambdaFunction-Unit-Tests.html
    - ExampleProjectPipelineSimple.yaml
    - ExampleProjectDeployPermissions.yaml
  secondary-artifacts:
    LambdaFunction:
      base-directory: 'publish/lambda'
      files:
        - '**/*'
