AWSTemplateFormatVersion: '2010-09-09'
Description: Cross account primary stack.
Parameters:
  DeploymentOrgPath:
    Description: A comma separated list of OUs that can be deployed to. This OUs will have access to the pipeline artifacts.
    Type: String
Resources:
  # This KMS key is for use with the cross account build/deploment. The permissions allow the
  # CrossAccount-CodePipeline role within the deployment organization to use the key.
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Used by Assumed Roles in deploy accounts to Encrypt/Decrypt code
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Ref AWS::StackName
        Statement:
          - Sid: Allows admin of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource: '*'
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn: arn:aws:iam::*:role/cross-account-service-role/*
              ForAnyValue:StringLike:
                aws:PrincipalOrgPaths:
                  Fn::Split:
                    - ','
                    - !Ref DeploymentOrgPath

  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/codepipeline-crossaccounts
      TargetKeyId: !Ref KMSKey

  # Topic to be used for manual intervention notification in a pipeline.
  ManualInterventionTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Topic for pipeline manual intervention notifications
      TopicName: PipelineManualIntervention

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccount-CodeBuild
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /cross-account-service-role/
      ManagedPolicyArns:
        - !Ref CodeBuildPolicy

  CodeBuildPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for Cross Account CodeBuild projects
      ManagedPolicyName: CrossAccount-CodeBuild
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
            Effect: Allow
          - Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - !Sub arn:aws:s3:::${BuildBucket}
              - !Sub arn:aws:s3:::${BuildBucket}/*
            Effect: Allow

            # TODO: how best to handle things like this?
          - Action:
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource:
              - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:github-access-token-*
      Path: /cross-account-service-role/

  CrossAccountUpdatePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccount-UpdatePipeline
      Path: /cross-account-service-role/
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
      ManagedPolicyArns:
        - !Ref CrossAccountUpdatePipelinePolicy

  CrossAccountUpdatePipelinePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for Cross Account Update Pipeline
      ManagedPolicyName: CrossAccount-UpdatePipeline
      Path: /cross-account-service-role/
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - codebuild:CreateProject
              - codebuild:CreateWebhook
              - codebuild:DeleteProject
              - codebuild:DeleteSourceCredentials
              - codebuild:DeleteWebhook
              - codebuild:ImportSourceCredentials
              - codebuild:InvalidateProjectCache
              - codebuild:ListProjects
              - codebuild:ListSourceCredentials
              - codebuild:PutResourcePolicy
              - codebuild:UpdateProject
              - codebuild:UpdateWebhook

              - codepipeline:CreateCustomActionType
              - codepipeline:CreatePipeline
              - codepipeline:DeleteCustomActionType
              - codepipeline:DeletePipeline
              - codepipeline:DeleteWebhook
              - codepipeline:DeregisterWebhookWithThirdParty
              - codepipeline:GetPipeline
              - codepipeline:ListActionTypes
              - codepipeline:ListPipelines
              - codepipeline:ListTagsForResource
              - codepipeline:ListWebhooks
              - codepipeline:PutActionRevision
              - codepipeline:PutWebhook
              - codepipeline:RegisterWebhookWithThirdParty
              - codepipeline:TagResource
              - codepipeline:UntagResource
              - codepipeline:UpdatePipeline
              - codepipeline:StartPipelineExecution
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - logs:*LogGroup
            Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource:
              - arn:aws:iam::*:role/cross-account-service-role/*

  # This is the bucket where build artifacts are put. CodeBuild should place things here, and
  # CodePipeline should trigger off specific artifacts.
  BuildBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !GetAtt KMSKey.Arn
              SSEAlgorithm: aws:kms

  # This is the bucket that is used for CodePipeline, in the primary region
  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !GetAtt KMSKey.Arn
              SSEAlgorithm: aws:kms

  # Grant access to the cross account CloudFormation and CodePipeline roles within the deployment
  # organization
  PipelineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PipelineBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${PipelineBucket}
              - !Sub arn:aws:s3:::${PipelineBucket}/*
            Principal: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn: arn:aws:iam::*:role/cross-account-service-role/*
              ForAnyValue:StringLike:
                aws:PrincipalOrgPaths:
                  Fn::Split:
                    - ','
                    - !Ref DeploymentOrgPath

  # This role can be used as the pipeline source in any pipeline
  PipelineSourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccount-PipelineSource
      Path: /cross-account-service-role/
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
      ManagedPolicyArns:
        - !Ref PipelineSourcePolicy

  # This policy grants the pipeline source permission to access the S3 buckets for build and pipelines
  # as well as permission to use the KMS key, assume the CrossAccount-PipelineSource role and passrole to the CrossAccount-PipelineSource role
  PipelineSourcePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CrossAccount-PipelineSource
      Path: /cross-account-service-role/
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - cloudformation:*
            Effect: Allow
            Resource: '*'
          - Action:
              - s3:GetBucketLocation
              - s3:List*
              - s3:Get*
              - s3:Put*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${BuildBucket}
              - !Sub arn:aws:s3:::${BuildBucket}/*
              - !Sub arn:aws:s3:::${PipelineBucket}
              - !Sub arn:aws:s3:::${PipelineBucket}/*
          - Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey*
            Effect: Allow
            Resource:
              - !GetAtt KMSKey.Arn
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/cross-account-service-role/CrossAccount-PipelineSource
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/CrossAccount-PipelineSource

Outputs:
  CMK:
    Description: The CMK that is used for cross account access
    Value: !GetAtt KMSKey.Arn
    Export:
      Name: CrossAccountCMK
  BuildBucket:
    Description: The bucket for the builds
    Value: !Ref BuildBucket
    Export:
      Name: BuildBucket
  PipelineBucket:
    Description: The bucket for the pipeline
    Value: !Ref PipelineBucket
    Export:
      Name: PipelineBucket
  ManualInterventionTopicArn:
    Description: The manual intervetion topic ARN
    Value: !Ref ManualInterventionTopic
    Export:
      Name: ManualInterventionTopicArn
  PipelineSourceRoleArn:
    Description: The ARN of the pipeline source role
    Value: !GetAtt PipelineSourceRole.Arn
